name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        uses: elgohr/Publish-Docker_Github_Action@master
        with:
          registry: https://ghcr.io
          name: docker.png.github.com/thedeemoonn/stepbystep/stepbystep
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"

